### ISSUE TITLE
Question, will tha options inna tha quickichat menu be able'ta change? 

### ISSUE THREAD

**Issue by Flloppis** [MelonBoyy/Lethal_Company_Mod-Quick_Chat#1]
Like'an option for you to changey whats said inna each categori? 
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/9d134559-5516-4542-8dcb-cd243a339569)
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/f42c376b-3885-4d16-8ff9-329273d2afa3)

**Comment by MelonBoyy** [comment]
With the way the menus are made I can definitely make that a feature in LethalConfig. I am on a break currently though. I will release an update to customize the menu a bit afterwards.

**Comment by Flloppis** [comment]
Ooo!! Thanki you!! :>

**Comment by MelonBoyy** [comment]
You very welcome, Mr. Flop!

**Comment by MelonBoyy** [comment]
> Like'an option for you to changey whats said inna each categori? ![image](https://private-user-images.githubusercontent.com/157853816/300132176-9d134559-5516-4542-8dcb-cd243a339569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTU5MzEsIm5iZiI6MTcwNjk5NTYzMSwicGF0aCI6Ii8xNTc4NTM4MTYvMzAwMTMyMTc2LTlkMTM0NTU5LTU1MTYtNDU0Mi04ZGNiLWNkMjQzYTMzOTU2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMTI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGI0MzNiYzY1MDg1OWQ1MDU5YzVmMzI3M2Q1MDFhZDk5NjRjMzc3NTE0NjdkY2Q1NmM2ZDkyZjQ2MDUyY2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k51K-FhzZZm3mAyL-8ryxePz7NA86V2Dw4oNluARWN4) ![image](https://private-user-images.githubusercontent.com/157853816/300132276-f42c376b-3885-4d16-8ff9-329273d2afa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTU5MzEsIm5iZiI6MTcwNjk5NTYzMSwicGF0aCI6Ii8xNTc4NTM4MTYvMzAwMTMyMjc2LWY0MmMzNzZiLTM4ODUtNGQxNi04ZmY5LTMyOTI3M2QyYWZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QyMTI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTZmYmVhZjYxNGNkMWU1OTc0MmFhNDVmYjQxMDhhYTYxYTg2MTlkYzZjZWRmZTNlYzY2Y2VmNDE2Mzc5N2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._yK8RG3eEaECck5TOg1Ny2Tl_Akaj8_b7LuuaZfQCho)

It appears I misread what you typed. It is possible to do so but so far i'm only gonna allow color changes. Any changes through a config would be extremely cluttered unless I create my own custom menu which is not in my current scope (I apologize). I will create configs for changing colors of the defaultmenu but other than that i'm not working on changing text. Others may feel free to change text or create custom menus in their own mods once I complete documentation. Sorry once again, I apologize sincerely.
