### ISSUE TITLE
Questionni 2 ( Sorri ;< ) How'di exporti me changes inta me mods folderri?

### ISSUE THREAD

**Issue by Flloppis** [MelonBoyy/Lethal_Company_Mod-Quick_Chat#2]
Sorri forra 'nother questionni.
I wassa able ta change tha text inna document, but howdi put it inta me mods folder onna Thunderstore Mod Manager? Theresi-- this dll file.. I havvi no idea what ta do-.. What programmi shouldi use?

**Comment by MelonBoyy** [comment]
I recommend using r2modman to install mods easily. Either that or find a tutorial for downloading mods manually although I just recommend r2modman. It's okay to put questions here but I recommend going to the Lethal Company Modding Discord and sending me questions in the QuickChat mod-releases forum. https://discord.gg/lcmod

**Comment by Flloppis** [comment]
OO!! Ah foundi out how'ta do it!!! :D
Ah wenti inta tha r2modmansi profile folderri thing- went ta yerra oney, found tha .dll file anda usedi dnSpy ta editti tha words and save itta back'ta tha folder!!!!!!!!
Thanksi yer for'ya helpi!!!
