### ISSUE TITLE
Camera Bugsi aftersi bein' kicked orra host crashin'

### ISSUE THREAD

**Issue by Flloppis** [MelonBoyy/Lethal_Company_Mod-Quick_Chat#3]
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/76e4899d-ea99-45e7-a651-a0faac918871)
Afterra bein' kicked or tha host crashin'
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/554de877-05a7-4f4b-8c7e-caaf5db01409)
When ya join 'nother lobby.
- There willa be PREVIEW text infront of'ya character model
- Openin' tha QuickChat menu will notta showsi tha gui button
- Ya will havesi bugged gravity
- ESC key notta workin' ta exitti pause menu.
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/67993d0f-5807-4aae-82c8-03cdabfadd7a)
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/06e421ca-cc45-413b-86ac-01e6f9207b8d)
Tha darkenin' of tha screen wontsi go awayya too and buttonsi wont work when'ya inna pause menu
Andi tha onlii way ta fix is'ta restart tha game.

Heresi me console errorsi 
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/d3e8b7c0-7305-4137-85d6-6cebe12e1f40)

**Comment by Flloppis** [comment]
![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/726a94d7-1188-4f98-8030-8aee8db8c5f4)

![image](https://github.com/MelonBoyy/Lethal_Company_Mod-Quick_Chat/assets/157853816/4f6dd412-efc0-4625-81db-4c85aca77d30)
Anda lotta log spammin'

**Comment by MelonBoyy** [comment]
I'll try to fix this when I get the chance to.

**Comment by MelonBoyy** [comment]
Fixed in Version 2.1.1
